### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by mrkaban** [diskcryptor/DiskCryptor#2]
Google Chrome and the Yandex browser do not allow you to download your version of DiskCryptor - they say that it is a virus.

**Comment by DavidXanatos** [comment]
This to be fixed requires a few 1000€ for an EV Code signing certificate.

I for myself consider that a waste of money; eider you trust the tool or you don't.

In any case you shouldn't allow any browser to patronize you.

**Comment by mrkaban** [comment]
I agree with you, but you need to think carefully about some option, because none of my browsers has let "DiskCryptor" download. I really like that you continue this project! It is very cool! Especially in light of the fact that their site has become unavailable. However, you also understand me, I can’t give a link to download this file, since for me it will be a direct path to the negative consequences of the search engines.

Is a portable version possible? in the case of "TaskExplorer" this solves the problem.

**Comment by DavidXanatos** [comment]
hmm... I see, here is a solution:
https://github.com/diskcryptor/DiskCryptor/releases/download/v1.2.1/dcrypt_setup_1.2_beta_2.zip
zipped with a password so it should be fine as now the installer can't be read hence the download should succeed.

About linking and the "negative consequences of the search engines."
how about linking only to the github release: https://github.com/diskcryptor/DiskCryptor/releases/tag/v1.2.1
instead of the direct download?
Linking to https://github.com/diskcryptor/DiskCryptor/releases/ would be even better as there you have always the newest release on top.

About obtaining a EV certificate, I'm looking into the options, may be someone with one with one will be so kind to sign my releases.

**Comment by mrkaban** [comment]
Thank you, archiving with a password is already at least some solution.

In the description of the program, I made a link to your fork (here is the link).

I still need direct links, if you don’t do them, a lot of indicators immediately fall.

**Comment by DavidXanatos** [comment]
Ok good to know :-)
I will, until I have a better solution, always pack and encrypt the installer.

I think what I should go for in the short term will be an own custom installer, for TaskExplorer this seams to work ok. But for DCrypt I need a substantially better tool such that it handles the driver upgrade.

**Comment by andika207** [comment]
@mrkaban Yes. Hitman Pro detects it as ransomware I have already deleted it forever.

**Comment by andika207** [comment]
@DavidXanatos your name was very familiar to me, I think you are the same of the MSFN forum in which there was another discussion about one of your programs being infected... do you make anything useful virus free ?????

**Comment by DavidXanatos** [comment]
> 
> 
> @DavidXanatos your name was very familiar to me, I think you are the same of the MSFN forum in which there was another discussion about one of your programs being infected... do you make anything useful virus free ?????

Its all virus free, just the drivers are signed using leaked certificates, and those are also used by many virus authors.
I use its because its free, why wasting 500€/year on a microsoft kernel tax
thay use it because its anonymuse.
thats all.

**Comment by andika207** [comment]
@DavidXanatos bla bla bla...there is a good reason why I got infected when installing the other utility.
