### ISSUE TITLE
 Build v1.2 Beta 3 bootloader BUG

### ISSUE THREAD

**Issue by liskaaaaaaaaaa** [diskcryptor/DiskCryptor#4]
Beta 2 (good version)
https://www27.zippyshare.com/v/LXDRpBFi/file.html

Beta 3 
https://www11.zippyshare.com/v/5qJ4V9Ll/file.html

Please fix it

**Comment by DavidXanatos** [comment]
You want the password to get cleared when enter is pressed and the password was wrong?

The new behavior was intended as an improvement, as now you can also edit the entered password:
Press f5 to see it (toogle bwteen display and ***) what was in beta 1 and 2, now in 3
you can use arrow keys to navigate the string and overwrite characters, del to remove them and insert to insert a space that you than can override with some other.

Its always very annoying to type in a long password and when its wrong to repeat it 3 times until you decide to sit down and type it in; one character at a time.
And often the issue is that the shift key did not take or my left and right hand ran out of sync and a pair of letters got swapped.
Now with this new feature I can display the password and fix the typo.

If you press esc the password will be cleared form memory anyways.

I could improve it such that if you press backspace on a new prompt with the wrong password it will delete the entire password once.

**Comment by liskaaaaaaaaaa** [comment]
> You want the password to get cleared when enter is pressed and the password was wrong?

Yes. 
Because of this audit, VeraCrypt has issued a number of fixes to both the application and the bootloader in 1.19.
- Fixes implemented for the vulnerability described in section 7.1 for the new bootloader. (keystrokes not erased after authentication)

**Comment by DavidXanatos** [comment]
Since the DC UEFI loader is based on the VeraCrypt's one from the latest build all that issues are fixed as well.
